### ISSUE TITLE
5 - Add checkboxes for task list and delete task on click of check box

### ISSUE THREAD

**Issue by kaseyliu** [elhagen13/StudyWell#5]
Create a task react component. This will include a text box and a check box. It should be able to create multiple task boxes, and be deleted once the check box is clicked.

**Comment by SabaHakimi** [comment]
Added checkbox
- Applies strikethrough on text when checkmark is clicked.

**Comment by SabaHakimi** [comment]
Expected: 1 hr
Actual: 2 hr
